package:
  name: menpowidgets
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo >=0.9.0,<0.12.0
    - ipywidgets
    - ipyevents

test:
  imports:
  - menpowidgets

about:
  home: https://github.com/menpo/menpowidgets/
  license: BSD 3-Clause
  summary: The Menpo Project Python package for visualizing data using Jupyter widgets
  description: |
    A library inside the Menpo Project that makes visualizing data inside
    Jupyter notebooks simple. It supports a number of useful widgets for visualizing
    both images and meshes.
  doc_url: https://menpowidgets.readthedocs.io/en/stable/
  dev_url: https://github.com/menpo/menpowidgets
