name: menpowidgets_rtd
channels:
  - conda-forge
dependencies:
  - python 3.7.*
  - setuptools
  - ipywidgets
  - menpo

  # Docs Only
  - sphinx >=2,<3
  - sphinx_rtd_theme
  - pip:
      - sphinxmapxrefrole>=0.2
